### ISSUE TITLE
[BUG] Typings missing for axe-webdriverjs

### ISSUE THREAD

**Issue by guerjon** [microsoft/axe-pipelines-samples#200] opened 2020-01-10 18:37 UTC
Please check whether the bug has [already been filed](https://github.com/Microsoft/accessibility-insights-windows/issues).

**TS lint on VSC can't find axe-webdriverjs**
After clone the project and install the dependencies, was reading in the file index.test.ts and realize that import * as AxeWebdriverjs from 'axe-webdriverjs'; was showing this error

This is also happening after try to implement in my own project. 

**To Reproduce**
1. Clone the project
2. Install dependencies
3. Go to index.test.ts with visual studio code

**Expected behavior**
Don't see the error

**Actual behavior**
This error is show Could not find a declaration file for module 'axe-webdriverjs'. 'c:/Users/v-jogue/axe-pipelines-samples/typescript-selenium-webdriver-sample/node_modules/axe-webdriverjs/dist/index.js' implicitly has an 'any' type.
  Try `npm install @types/axe-webdriverjs` if it exists or add a new declaration (.d.ts) file containing `declare module 'axe-webdriverjs';`

**Screenshots or .GIF**
![image](https://user-images.githubusercontent.com/25444342/72176872-4429fc00-3394-11ea-884a-fca004b110ff.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - VSC 1.41.1

**Comment by devaradhanm** [comment] 2020-01-10 19:24
Thanks for reporting this issue @guerjon . I see that axe-webdriverjs doesnt have typings. So, it is typecasted as 'any' type. You can still run the tests though, by running yarn install or by debugging in  vscode.
We will look into this issue. I found that @types/axe-webdriverjs seems to be not in sync with the latest version.

**Comment by adarshrema** [comment] 2020-01-18 02:06
Hello @guerjon, thank you for using one of our samples and for reporting this issue.

We do not maintain axe-webdriverjs, so technically this is not a bug at our end. However, we understand the user impact and are adding this to the backlog to contribute to the axe-wedriverjs package to update typings.

**Comment by ferBonnin** [comment] 2020-08-03 17:45
@adarshrema is this a bug or a feature request?

**Comment by adarshrema** [comment] 2020-08-03 18:34
Based on initial response to the issue, this does look like a bug size effort. Adding @dbjorge  to confirm.

**Comment by karanbirsingh** [comment] 2021-04-19 22:32
Current state:
- Deque merged https://github.com/dequelabs/axe-core-npm/pull/197 which covers issue 30 above
- The change will be in @axe-core/webdriverjs 4.1.2 (unreleased)
- Once 4.1.2 is released, we can update our usage here

For users wanting to work around this, they can work with a preview version of 4.1.2 - described in more detail at https://github.com/dequelabs/axe-core-npm/issues/195

Marking as blocked until version 4.1.2 of [@axe-core/webdriverjs](https://www.npmjs.com/package/@axe-core/webdriverjs) is released

**Comment by ferBonnin** [comment] 2021-08-30 17:47
@karanbirsingh @dbjorge is this still blocked?

**Comment by dbjorge** [comment] 2021-08-30 17:55
It's actually already resolved (we migrated to a fixed version of @axe-core/webdriverjs in #543 back in May)

**Closed** 2021-08-30 17:56 UTC
Labels: bug, status: resolved
